; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=gPodder
AppVerName=gPodder 0.10.4svn-win32
AppPublisher=Thomas Perl
AppPublisherURL=http://gpodder.berlios.de/
AppSupportURL=http://gpodder.berlios.de/
AppUpdatesURL=http://gpodder.berlios.de/
DefaultDirName={pf}\gPodder
DefaultGroupName=gPodder
OutputBaseFilename=gpodder-0.10.3-win32-setup
Compression=lzma
SolidCompression=yes
AllowUNCPath=false

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Dokumente und Einstellungen\Administrator\Desktop\gpodder\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\gPodder"; Filename: "{app}\gpodder.exe"
Name: "{group}\{cm:ProgramOnTheWeb,gPodder}"; Filename: "http://gpodder.berlios.de/"
Name: "{group}\{cm:UninstallProgram,gPodder}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\gPodder"; Filename: "{app}\gpodder.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\gpodder.exe"; Description: "{cm:LaunchProgram,gPodder}"; Flags: nowait postinstall skipifsilent

