#!/bin/sh
# Small wrapper to crop widescreen Youtube 3gp videos (and others)
# Used by gPodder if available and player is set to "mplayer"
# Thomas Perl <thpinfo.com> 2009-09-09

CROP_PARAM=`mplayer -ss 5 -frames 5 -vo null -ao null -vf cropdetect "$1" 2>/dev/null | grep -o -- '-vf crop=[^)]*' | tail -n1`

mplayer $CROP_PARAM "$1"

