.TH GPO "1" "September 2012" "gpodder 2.20.2" "User Commands"
.SH NAME
gpo \- Command\-line frontend to gPodder
.SH SYNOPSIS
.B gpo
\fICOMMAND\fR [\fIparams...\fR]
.SH DESCRIPTION
.PP
This is the command\-line frontend to gPodder. Run the command without
parameters to show an overview of possible options and sub\-commands.
.SH BUGS
.PP
Some commands are not yet implemented. Also, this manual page is quite empty.
Feel free to contribute documentation and/or code for this utility. See the
gPodder website at http://gpodder.org for more information.
