.TH GPODDER-MIGRATE2TRES "1" "May 2012" "gpodder 3.2.0" "User Commands"
.SH NAME
gpodder-migrate2tres \- gpodder 2.x to 3.x profile migrator
.SH SYNOPSIS
.B gpodder-migrate2tres
.SH DESCRIPTION
Command-line utility to migrate user's gPodder 2.x configuration data for
use with gPodder 3.x.  Invoke the command with no options to migrate the
configuration data for the current user.  Feedback is provided.
.PP
The gpodder-backup utility (included with gPodder 2.x) can be used to
backup the configuration prior to migration.  There isn't currently a
migration from gPodder 3.x to gPodder 2.x.
