#! /bin/sh

# We have to update the icon cache
gtk-update-icon-cache -f /usr/share/icons/hicolor

oldversion="$2"
if [ -z "$oldversion" ]; then
	maemo-select-menu-location gpodder.desktop
fi

#DEBHELPER#

