name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@0727cc2cdf0f3ecafd492608d2aff67b13adff55
        with:
          identifier: gpodder.gpodder
          version-regex: '[0-9.]+'
          installers-regex: 'installer\.exe$' # only the installer.exe file
          token: ${{ secrets.WINGET_TOKEN }}
