name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@1492f6c8620789a03865436b2eb95c6a944f8405
        with:
          identifier: gpodder.gpodder
          version-regex: '[0-9.]+'
          installers-regex: 'installer\.exe$' # only the installer.exe file
          token: ${{ secrets.WINGET_TOKEN }}
